---
version: 2.0

jobs:
  build:
    docker:
      - image: python:2.7
    environment:
      DEBIAN_FRONTEND: noninteractive
      FIXTURES_NO_RECORD: 1
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            # Install gettext
            apt-get update -q -y
            apt-get install -q -y gettext

            pip install cram
            pip install rpm_vercmp
      - run:
          name: Test
          command: make test
